"""Added 2 cols

Revision ID: 9a3eecf3403b
Revises: ea07defc3767
Create Date: 2025-11-28 18:58:28.221718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3eecf3403b'
down_revision: Union[str, Sequence[str], None] = 'ea07defc3767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('from_value', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('to_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'to_value')
    op.drop_column('activities', 'from_value')
    # ### end Alembic commands ###
